### ISSUE TITLE
cuhk-pedes，data preprocess？

### ISSUE THREAD

**Issue by AbeanYang97** [hwz-zju/Instruct-ReID#22]
请问下作者，cuhkpedes的数据预处理脚本能分享一下吗？datalist里的需要的query gallery train的txt文件，源数据集里没有

**Comment by graco-pan** [comment]
> 请问下作者，cuhkpedes的数据预处理脚本能分享一下吗？datalist里的需要的query gallery train的txt文件，源数据集里没有

你好请问您知道怎么处理了么，可不可以分享一下
