### ISSUE TITLE
环境版本

### ISSUE THREAD

**Issue by zerobest** [hwz-zju/Instruct-ReID#3]
能麻烦您提供一下环境中需要安装的库的版本吗，我在运行代码的时候发现 AttributeError: 'BertConfig' object has no attribute 'fusion_layer'这个问题

**Comment by CuriousTank** [comment]
It seems that this repo is not yet complete

**Comment by CuriousTank** [comment]
> It seems that this warehouse is not yet complete

Looking forward to providing more information

**Comment by hwz-zju** [comment]
Thank you for your feedback. We have updated the version information of the dependency packages. Please try again.
