### ISSUE TITLE
Hello, how much gpu memory is needed for reproduction？This determines whether we can follow up on this further.

### ISSUE THREAD

**Issue by leo-7879** [hwz-zju/Instruct-ReID#7]

**Comment by hwz-zju** [comment]
We set the batch size as 128, and the image size as 128*256. It takes about 20G GPU memory and we take only one NVIDIA V100 GPU for the Single-task Learning  and  32 NVIDIA V100 GPUS for Multi-task Learning.

**Comment by leo-7879** [comment]
Thanks for your reply, is it possible that multi-task learning can also be trained using 20G GPU memory if we set the batchsize  as the same as single-task, except that the training is slower.

**Comment by hwz-zju** [comment]
Yes, multi-task learning tasks similar GPU memory as single-task learning on each GPU.

**Comment by leo-7879** [comment]
Thanks for your reply. In this case，can I use one gpu (at least 20G) for training on multi-task learning tasks? Does the code contain mandatory requirements for parallel computing on multi-task learning?

**Comment by hwz-zju** [comment]
The GPU number is configured in the config_joint.yaml file, and it should be an integer multiple of the sum of all gres_ratio parameters
