### ISSUE TITLE
Does each dataset (e.g., there are N datasets) train to get N models and then tested separately using the corresponding model, or do all datasets train to get only a model?

### ISSUE THREAD

**Issue by leo-7879** [hwz-zju/Instruct-ReID#8]

**Comment by hwz-zju** [comment]
Yes, due to the 15GB storage limit on Google Drive, several checkpoint models did not appear. You can download the corresponding models from this new link. Among them, checkpoint_multi.pth.tar is the multi-task learning model.
link:https://pan.baidu.com/s/1ZL1a6Lj-U6SfFD9Pmt56Ww
code:3wne

**Comment by fspinola** [comment]
Hello @hwz-zju thanks a lot for the great work! I would be interested in using the multi-dataset trained model. But I don't have access to Baidu. Could you please upload it to Google Drive?
